In [26]:
import pandas as pd
import numpy as np
yorumlar=pd.read_csv("Restaurant reviews.csv")
yorumlar.head()

Restaurant              Reviewer  \
0  Beyond Flavours     Rusha Chakraborty   
1  Beyond Flavours  Anusha Tirumalaneedi   
2  Beyond Flavours       Ashok Shekhawat   
3  Beyond Flavours        Swapnil Sarkar   
4  Beyond Flavours                Dileep   

                                              Review Rating  \
0  The ambience was good, food was quite good . h...      5   
1  Ambience is too good for a pleasant evening. S...      5   
2  A must try.. great food great ambience. Thnx f...      5   
3  Soumen das and Arun was a great guy. Only beca...      5   
4  Food is good.we ordered Kodi drumsticks and ba...      5   

                  Metadata             Time  Pictures    7514  
0   1 Review , 2 Followers  5/25/2019 15:54         0  2447.0  
1  3 Reviews , 2 Followers  5/25/2019 14:20         0     NaN  
2  2 Reviews , 3 Followers  5/24/2019 22:54         0     NaN  
3    1 Review , 1 Follower  5/24/2019 22:11         0     NaN  
4  3 Reviews , 2 Followers  5/24/2019 21:37         0     NaN

In [27]:
import re

In [28]:
yorum=re.sub("[^a-zA-Z]"," ",yorumlar["Review"][0])#sub değiştir gibi yani replace görevi görür [a-zA-Z] normalde küçük ve büyük adan z ye kadar
#hepsini filtrele demek [^a-zA-Z] yaparsak bunlar dışındakileri filtrele yani . , falan , şimdi bunlara ne yaptıracağımız yazılır


In [5]:
yorum

'The ambience was good  food was quite good   had Saturday lunch   which was cost effective   Good place for a sate brunch  One can also chill with friends and or parents  Waiter Soumen Das was really courteous and helpful '

In [29]:
yorum=yorum.lower()
yorum

'the ambience was good  food was quite good   had saturday lunch   which was cost effective   good place for a sate brunch  one can also chill with friends and or parents  waiter soumen das was really courteous and helpful '

In [30]:
yorum=yorum.split()
yorum

['the',
 'ambience',
 'was',
 'good',
 'food',
 'was',
 'quite',
 'good',
 'had',
 'saturday',
 'lunch',
 'which',
 'was',
 'cost',
 'effective',
 'good',
 'place',
 'for',
 'a',
 'sate',
 'brunch',
 'one',
 'can',
 'also',
 'chill',
 'with',
 'friends',
 'and',
 'or',
 'parents',
 'waiter',
 'soumen',
 'das',
 'was',
 'really',
 'courteous',
 'and',
 'helpful']

In [31]:
import nltk

In [32]:
from nltk.corpus import stopwords

In [33]:
from nltk.stem.porter import PorterStemmer

In [38]:
derle=[]

In [41]:
for i in range(0,1000): #1000 boyutlku var
        yorum=re.sub("[^a-zA-Z]"," ",yorumlar["Review"][i])
        yorum=yorum.lower()
        yorum=yorum.split()
        ps=PorterStemmer()
        yorum=[ps.stem(kelime) for kelime in yorum if not kelime in set(stopwords.words("english"))]
        yorum = ' '.join(yorum) #yorumu al boşluklarla birleştir
        derle.append(yorum)

In [42]:
derle

['ambienc good food quit good saturday lunch cost effect good place sate brunch one also chill friend parent waiter soumen da realli courteou help',
 'ambienc good pleasant even servic prompt food good good experi soumen da kudo servic',
 'must tri great food great ambienc thnx servic pradeep subroto person recommend penn alfredo pasta also music background amaz',
 'soumen da arun great guy behavior sincereti good food cours would like visit place',
 'food good order kodi drumstick basket mutton biryani good thank pradeep serv well enjoy ambienc also good',
 'ambianc good servic good food apradeecp subro best servic food good papiya good hostess ur caption good star restaur',
 'nice place ambienc differ food order tasti servic also gud worth visit reason well realli must visit place',
 'well read mani review final visit place ambienc good come food crispi corn nice tawa fish ok basket biryani disappoint us biryani ok flatter claim staff polit prompt especi pradeep suman',
 'excel food 

In [94]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=2000)
X=cv.fit_transform(derle).toarray() # 0 ve 1 e indirdik yani pozitif negatif var yok
y= yorumlar["Rating"][:1000] #for range 1000 e kadar listeye eklettik sonucunda X olarak 1000 boyutu olan listeyi fit ettik
# y 10000 boyutluydu 1000 e idirgedik bu şekil

In [83]:
from sklearn.model_selection import train_test_split
X.shape

(1000, 2000)

In [85]:
y.shape #şu an böyle ama boyut hatası veriypr   chatgptnin sunduğu bu

(1000,)

In [96]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42) 

In [50]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [88]:
from sklearn.naive_bayes import GaussianNB

In [97]:
gnb=GaussianNB()

In [99]:
gnb.fit(X_train,y_train)#fit eğitmektir  xtrainden öğren y traine örendikten sonra tahmin et   trainler %80lik kısımdır 
y_pred = gnb.predict(X_test)#şimdi ½20lik kısım tahmin  yani yorumlardaki 1 ve 0ları tahmin et  ytestte bizim gerçek değerlerimiz
#bakalım ne kadar doğru çıkarmış  ilişki içinde confusion matrix kullanacam
cm=confusion_matrix(y_test,y_pred) #birbirleri arasındaki ilişki , bakalım ne kadar iyi tahmin etmiş  tahminler ile gerçekler arasında
print(cm) #68 20  2ye 2 lik matris çıktı ve 95+68 /2  yaptı accuracy başarı oranı yani tahmin oranını bbuldu 
          #30 95  30 +20 /2 yappıp 25 ile hata oranı buldu

[[11  2  1  8  5]
 [ 2  1  2  1  2]
 [ 2  1  3  7  6]
 [ 3  0  1 26 14]
 [ 2  2  6 33 59]]
